controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

app_login_cha_web:
  path: /login
  controller: App\Controller\LoginController::index

events:
  path: /event
  controller: App\Controller\EventController::index

users:
  path: /user
  controller: App\Controller\UserController::index